config/routes.rb
Rails.application.routes.draw do
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    post '/users', to: 'users#create'
    devise_for :users, controllers: { confirmations: 'users/confirmations', omniauth: 'users/omniauth', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions', unlocks: 'users/unlocks' }, constraints: { format: :html }

    resources :page_sections

    resources :tags

    resources :prisons do
      collection do
        get 'prison_prisoner_counts', constraints: { format: :json }, defaults: { format: :json }
      end
    end

    resources :criminal_codes

    resources :articles do
      collection do
        get 'article_incident_counts', constraints: { format: :json }, defaults: { format: :json }
      end
    end

    resources :prisoners do
      collection do
        get 'incidents_to_csv', constraints: { format: :csv }, defaults: { format: :csv }
        get 'imprisoned_count_timeline', constraints: { format: :json }, defaults: { format: :json }
      end

      resources :incidents, except: [:index, :show]
    end

    resources :users, constraints: { format: :html }

    # root paths
    get '/about', to: 'root#about'
    get '/methodology', to: 'root#methodology'
    get '/disclaimer', to: 'root#disclaimer'
    get '/csv_zip', to: 'root#to_csv_zip', constraints: { format: :csv }, defaults: { format: :csv }

    # home page
    root 'root#index'

    get '*path', to: redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
  end

  get '', to: redirect("/#{I18n.default_locale}") # handles /
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/activerecord/article.rb
# An official article of law
class Article < ActiveRecord::Base
  include StringOutput
  extend FriendlyId

  belongs_to :criminal_code
  has_many :charges, dependent: :destroy
  has_many :incidents, through: :charges

  # strip extra spaces before saving
  auto_strip_attributes :number, :description

  translates :description, fallbacks_for_empty_translations: true
  # Allows reference of specific translations, i.e. post.title_az
  # or post.title_en
  globalize_accessors

  validates :number, :criminal_code, presence: true
  validates_uniqueness_of :number,
                          scope: :criminal_code,
                          message: I18n.t('article.errors.already_exists_for_criminal_code')

  # permalink
  friendly_id :number_and_code, use: :history
  def number_and_code
    "#{number}-in-#{criminal_code.name_en}-code"
  end

  def should_generate_new_friendly_id?
    number_changed? || criminal_code_id_changed? || slug.nil?
  end

  scope :with_criminal_code, -> { includes(:criminal_code) }

  def self.to_csv
    require 'csv'

    CSV.generate do |csv|
      csv << [
        I18n.t('activerecord.attributes.article.number'),
        I18n.t('activerecord.attributes.article.criminal_code'),
        I18n.t('activerecord.attributes.article.description')
      ]

      all.includes(:criminal_code)
        .order(criminal_code_id: :asc, number: :asc).each do |article|
        csv << [article.number,
                article.criminal_code.name,
                remove_tags(article.description)]
      end
    end
  end

  ############################################################
  ############ Article Charge Counts Chart ###################

  def self.summary(article_number, charge_count, code_name, desc)
    I18n.t('article.incident_counts_chart.summary',
           article_number: "<strong>##{article_number}</strong>",
           code_name: code_name,
           code_label: I18n.t('activerecord.models.criminal_code',
                              count: 1),
           number_of_incidents: "<strong>#{charge_count}</strong>",
           article_desc: desc)
  end

  def self.charge_counts_chart_data(limit = nil)
    # Get number of charges per article
    counts = Charge.limit(limit).group(:article_id).order('count_all desc').count

    # Get articles with criminal codes and translations. By using preload
    # instead of joins, further sql queries are not necessary to retreive the
    # translations
    articles = Article.preload(:translations, criminal_code: :translations).where(id: counts.keys)

    # Merge article info with charge counts
    articles_data = []

    counts.keys.each do |article_id|
      article = articles.find { |art| art.id == article_id }
      charge_count = counts[article.id]

      articles_data.append(
        y: charge_count,
        number: article.number,
        link: "/#{I18n.locale}/articles/#{article.slug}",
        summary: summary(article.number,
                         charge_count,
                         article.criminal_code.name,
                         article.description)
      )
    end

    articles_data
  end

  def self.charge_counts_chart_text
    {
      explore_charges: I18n.t('article.incident_counts_chart.static_text.explore_charges'),
      title: I18n.t('article.incident_counts_chart.static_text.title'),
      x_axis_label: I18n.t('article.incident_counts_chart.static_text.x_axis_label'),
      y_axis_label: I18n.t('article.incident_counts_chart.static_text.y_axis_label'),
      articles_path: Rails.application.routes.url_helpers
        .articles_path(locale: I18n.locale),
      highcharts: I18n.t('highcharts')
    }
  end

  def self.charge_counts_chart
    chart_data = {
      data: charge_counts_chart_data(10),
      text: charge_counts_chart_text
    }
  end

  def self.generate_charge_counts_chart_json(charge_counts_chart_json_path)
    # if folder path does not exist, create it
    FileUtils.mkdir_p(Pathname.new(File.dirname(charge_counts_chart_json_path)))

    File.open(charge_counts_chart_json_path, 'w') do |f|
      f.write(charge_counts_chart.to_json)
    end
  end

  def self.charge_counts_chart_json
    charge_counts_chart_json_path =
      Rails.public_path.join('generated',
                             'json',
                             I18n.locale.to_s,
                             GeneratedFile.clean_filename('article_incident_counts_chart', 'json'))

    unless File.exist?(charge_counts_chart_json_path)
      generate_charge_counts_chart_json(charge_counts_chart_json_path)
    end

    charge_counts_chart_json_path
  end

  def desc
    description.present? ? ActionController::Base.helpers.strip_tags(description) : I18n.t('article.errors.no_description')
  end

  # include the current prisoner count with the article
  def self.with_current_and_all_prisoner_count(article_id = nil)
    # this old query counts number of incidents, not people
    # sql = 'select a.*, if(i_current.count is null, 0, i_current.count) as
    # current_prisoner_count, if(i_all.count is null, 0, i_all.count) as
    # all_prisoner_count from articles as a left join (select article_id,
    # count(*) as count from charges group by article_id) as i_all on
    # i_all.article_id = a.id left join (select article_id, count(*) as
    # count from charges as c inner join incidents as i on i.id = c.incident_id
    # where i.date_of_release is null group by c.article_id) as i_current on i_
    # current.article_id = a.id'
    sql = 'select a.*, if(i_current.count is null, 0, i_current.count) as
    current_prisoner_count, if(i_all.count is null, 0, i_all.count)
    as all_prisoner_count  from articles as a  left join (select x.article_id,
    count(*) as count from (select c.article_id from charges as c  inner join
    incidents as i on i.id = c.incident_id  group by c.article_id,
    i.prisoner_id) as x group by x.article_id) as i_all on
    i_all.article_id = a.id  left join (select article_id, count(*)
    as count from charges as c inner join incidents as i on i.id = c.incident_id
    where i.date_of_release is null group by c.article_id) as
    i_current on i_current.article_id = a.id'
    sql << ' where a.id = ?' if article_id.present?
    find_by_sql([sql, article_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :redirect_to_newest_url, only: [:show, :edit, :update, :destroy]

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  authorize_resource

  before_action :set_prisoners_with_article, only: [:show]
  before_action :set_gon_variables

  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.includes(:criminal_code)
    @articles = Article.with_current_and_all_prisoner_count

    respond_to do |format|
      format.html
      format.json
      format.csv do
        send_data Article.to_csv,
                  filename: GeneratedFile.clean_filename('articles', 'csv'),
                  type: 'text/csv'
      end
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article_with_counts = Article.with_current_and_all_prisoner_count(@article.id).first
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html do
          redirect_to @article,
                      notice: t('shared.msgs.success_created',
                                obj: t('activerecord.models.article', count: 1))
        end
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json do
          render json: @article.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html do
          redirect_to @article,
                      notice: t('shared.msgs.success_updated',
                                obj: t('activerecord.models.article', count: 1))
        end
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html do
        redirect_to articles_url,
                    notice: t('shared.msgs.success_destroyed',
                              obj: t('activerecord.models.article', count: 1))
      end
      format.json { head :no_content }
    end
  end

  def article_incident_counts
    respond_to do |format|
      format.json { render json: File.read(Article.charge_counts_chart_json) }
    end
  end

  private

  # # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def set_prisoners_with_article
    @prisoners_with_article = Prisoner.by_article(@article.id)
  end

  def set_gon_variables
    gon.tinymce_config = YAML.load_file('config/tinymce.yml')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:number, :criminal_code_id, *Article.globalize_attribute_names)
  end

  # if request uses id instead of slug, corrects to use the right path
  def redirect_to_newest_url
    @article = Article.friendly.find params[:id]
    return false if request.path == (url_for action: action_name, id: @article.slug, only_path: true)
    redirect_to (url_for action: action_name, id: @article.slug, only_path: true), status: :moved_permanently
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% object = @article %>
<%= semantic_form_for(object) do |f| %>
  <%= f.semantic_errors *f.object.errors.keys %>
  <%= f.inputs do %>
    <%= f.input :number %>
    <%= f.input :criminal_code,
                hint: (link_to(t('shared.prompts.create_in_dropdown',
                                 obj: t('activerecord.models.criminal_code', count: 1)),
                       new_criminal_code_path,
                       target: '_blank')).html_safe %>

    <%= render layout: 'shared/form/translated_inputs',
               locals: { object: object } do |enabled_locale, enabled_locale_name| %>
      <%= f.input "description_#{enabled_locale}",
                  label: t('shared.labels.translated_field',
                           field: t('activerecord.attributes.article.description'),
                           language: enabled_locale_name),
                  as: :text,
                  input_html: { class: 'tinymce' } %>
    <% end %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, button_html: { class: 'btn btn-success' } %>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<% page_title t('shared.actions.with_obj.edit',
                obj: t('activerecord.models.article', count: 1)) %>

<% if user_signed_in? %>
  <div class='actions-container'>
    <%= render partial: 'shared/edit_actions',
          locals: {
            object: @article,
            index_path: articles_path,
            show_path: article_path
                  }
    %>
  </div>
<% end %>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<%
  model_class = Article
  page_title t('article.public.label', count: 999)
%>

<% if user_signed_in? %>
  <div class='actions-container'>
    <%= render partial: 'shared/index_actions',
               locals: {
                 model_class: model_class,
                 new_path: new_article_path
               }
    %>
  </div>
<% end %>

<%-
  datatable_class = (can? :edit, Article) ? 'datatable-article-admin' : 'datatable-article'
-%>
<table class="table table-striped table-hover table-nonfluid <%= datatable_class %>">
  <thead>
    <tr>
      <th></th>
      <th>
        <%= t('.column_label.code_number',
             code: t('activerecord.models.criminal_code', count: 1),
             article: t('activerecord.models.article', count: 1),
             number: t('activerecord.attributes.article.number')) %>
      </th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.column_label.currently_imprisoned_with_charge' %></th>
      <th><%=t '.column_label.total_imprisoned_with_charge' %></th>
      <% if can? :edit, Article %><th class="action-col"><%=t 'shared.common.actions' %></th><% end %>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to t('shared.actions.view'), article_path(article), class: 'btn btn-default' %></td>
        <td><%= article.criminal_code.name %> - <%= article.number %></td>
        <td><%= simple_format_no_tags(article.description) if article.description.present? %></td>
        <td><%= number_with_delimiter(article['current_prisoner_count']) %></td>
        <td><%= number_with_delimiter(article['all_prisoner_count']) %></td>
        <% if (can? :edit, article) || (can? :destroy, article) %>
          <td>
            <%= if can? :edit, article
                  link_to t('shared.actions.edit'),
                          edit_article_path(article),
                          class: 'btn btn-default'
            end %>
            <%= if can? :destroy, article
                  link_to t('shared.actions.destroy'),
                          article_path(article),
                          method: :delete,
                          data: { confirm: t('shared.prompts.confirm') },
                          class: 'btn btn-danger'
            end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<% page_title t('shared.actions.with_obj.new',
                obj: t('activerecord.models.article', count: 1)) %>

<% if user_signed_in? %>
  <div class='actions-container'>
    <%= render partial: 'shared/new_actions',
          locals: {
            object: @article,
            index_path: articles_path
                  }
    %>
  </div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%-
  model_class = Article
  page_title t('.title',
               arrest_charge: t('article.public.label', count: 1),
               article_number: @article.number,
               code_name: @article.criminal_code.name,
               code_model_name: t('activerecord.models.criminal_code', count: 1))
-%>

<% if user_signed_in? %>
  <div class='actions-container'>
    <%= render partial: 'shared/show_actions',
          locals: {
            object: @article,
            index_path: articles_path,
            show_path: article_path,
            edit_path: edit_article_path
                  }
    %>
  </div>
<% end %>
<div class='article-description'>
  <%= simple_format_no_tags(@article.description) if @article.description.present? %>
</div>

<div id="show-counts" class="row">
  <div class="col-sm-4 col-sm-offset-1">
    <div class="prisoner-count">
      <div class="count"><%= number_with_delimiter(@article_with_counts['current_prisoner_count']) %></div>
      <div class="intro intro-small"> <%=t '.counts.currently_imprisoned_with_charge' %></div>
    </div>
  </div>
  <div class="col-sm-4 col-sm-offset-2">
    <div class="prisoner-count">
      <div class="count"><%= number_with_delimiter(@article_with_counts['all_prisoner_count']) %></div>
      <div class="intro intro-small"> <%=t '.counts.total_imprisoned_with_charge' %></div>
    </div>
  </div>
</div>


<div class="datatable-topmargin">
  <table class="table table-striped table-hover datatable table-nonfluid">
    <thead>
      <tr>
        <th></th>
        <th><%=t '.column_label.all_people_charged_with_article' %></th>
        <th><%=t 'prisoner.total_days_in_prison' %></th>
      </tr>
    </thead>
    <tbody>
      <% @prisoners_with_article.each do |prisoner| %>
        <tr>
          <td><%= link_to t('shared.actions.view'), prisoner_path(prisoner), class: 'btn btn-default' %></td>
          <td><%= prisoner.name %></td>
          <td>
            <%= number_with_delimiter(prisoner.total_days_in_prison) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>