config/routes.rb
Rails.application.routes.draw do
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    post '/users', to: 'users#create'
    devise_for :users, controllers: { confirmations: 'users/confirmations', omniauth: 'users/omniauth', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions', unlocks: 'users/unlocks' }, constraints: { format: :html }

    resources :page_sections

    resources :tags

    resources :prisons do
      collection do
        get 'prison_prisoner_counts', constraints: { format: :json }, defaults: { format: :json }
      end
    end

    resources :criminal_codes

    resources :articles do
      collection do
        get 'article_incident_counts', constraints: { format: :json }, defaults: { format: :json }
      end
    end

    resources :prisoners do
      collection do
        get 'incidents_to_csv', constraints: { format: :csv }, defaults: { format: :csv }
        get 'imprisoned_count_timeline', constraints: { format: :json }, defaults: { format: :json }
      end

      resources :incidents, except: [:index, :show]
    end

    resources :users, constraints: { format: :html }

    # root paths
    get '/about', to: 'root#about'
    get '/methodology', to: 'root#methodology'
    get '/disclaimer', to: 'root#disclaimer'
    get '/csv_zip', to: 'root#to_csv_zip', constraints: { format: :csv }, defaults: { format: :csv }

    # home page
    root 'root#index'

    get '*path', to: redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
  end

  get '', to: redirect("/#{I18n.default_locale}") # handles /
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @app_intro = PageSection.find_by_name('app_intro')

    gon.imprisoned_count_timeline_prisoners_path = imprisoned_count_timeline_prisoners_path
    gon.article_incident_counts_articles_path = article_incident_counts_articles_path
    gon.prison_prisoner_counts_prisons_path = prison_prisoner_counts_prisons_path

    @featured_prisoner = Prisoner.where(currently_imprisoned: true).offset(rand(Prisoner.where(currently_imprisoned: true).count)).first
    @featured_prisoner_inc = (@featured_prisoner.blank?) || (@featured_prisoner.incidents.blank?) ? nil : @featured_prisoner.incidents.last

    @currently_imprisoned_count = Prisoner.currently_imprisoned_count
  end

  def about
    @project_description = PageSection.find_by_name('project_description')
  end

  def methodology
    @methodology = PageSection.find_by_name('methodology')
  end

  def disclaimer
    @disclaimer = PageSection.find_by_name('disclaimer')
  end

  def to_csv_zip
    send_file PwCsv.zip_all, type: 'application/zip'
  end
end

app/views/root/about.html.erb
<% page_title t('.title') %>

<div id="about">
  <%= simple_format_no_tags(@project_description.content) %>

  <p><%=t '.contributor_list_intro' %></p>

  <ul id="logos" class="list-inline">
    <li>
      <%= link_to(image_tag("about_js.png"),
                  "http://www.jumpstart.ge/en",
                  target: "_blank",
                  title: t('shared.common.jumpstart.slogan')) %>
    </li>
    <li>
      <%= link_to(image_tag("about_meydan.png"),
                  "http://www.meydan.tv/en",
                  target: "_blank",
                  title: t('shared.common.meydan.slogan')) %>
    </li>
  </ul>


  <p><%=t '.contact_intro' %></p>
  <p>
    <a href='ma&#105;l&#116;o&#58;info%40p%72ison%&#54;5rs&#46;w&#97;t%&#54;3h'>
      i&#110;&#102;o&#64;&#112;&#114;i&#115;oners&#46;&#119;&#97;t&#99;&#104;
    </a>
    (<a href="/Prisoners Watch info@prisoners.watch (0x8FB4E7CD) pub.asc">PGP</a>)
  </p>
</div>

app/views/root/disclaimer.html.erb
<% page_title t('.title') %>

<%= simple_format_no_tags(@disclaimer.content) %>

<p><%=t '.missing_or_incorrect_prompt' %></p>

<p>
  <a href='ma&#105;l&#116;o&#58;info%40p%72ison%&#54;5rs&#46;w&#97;t%&#54;3h'>
    i&#110;&#102;o&#64;&#112;&#114;i&#115;oners&#46;&#119;&#97;t&#99;&#104;
  </a>
  (<a href="/Prisoners Watch info@prisoners.watch (0x8FB4E7CD) pub.asc">PGP</a>)
</p>

app/views/root/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="prisoner-count">
      <div class="count">
        <%= number_with_delimiter(@currently_imprisoned_count) %>
      </div>
      <div class="intro">
        <%=t '.current_political_prisoners' %>
      </div>
      <div class="descr">
        <%= simple_format_no_tags(@app_intro.content) %>
        <p>
          <%= "#{t 'shared.last_updated'} #{l(Prisoner.data_last_updated, format: t('date.formats.long'))}" %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <% unless (@featured_prisoner.blank?) || (@featured_prisoner.incidents.blank?) %>
      <div id="featured-prisoner">
        <h2>
          <%= link_to(t('.meet_prisoner',
                        prisoner_name: @featured_prisoner.name),
                      prisoner_path(@featured_prisoner)) %>
        </h2>
        <div class="figure">
          <%= link_to image_tag(@featured_prisoner.portrait.url(:large)),
                      prisoner_path(@featured_prisoner) %>
        </div>
        <div class="info">
          <p>
            <strong>
              <%=t 'prisoners.labels.in_prison_since' %>
            </strong>
            <%= l @featured_prisoner_inc.date_of_arrest, format: :long %>
          </p>
          <% if @featured_prisoner_inc.prison.present? %>
            <p>
              <strong>
                <%=t 'prisoners.labels.imprisoned_at' %>
              </strong>
              <%= link_to @featured_prisoner_inc.prison.name,
                          prison_path(@featured_prisoner_inc.prison) %>
            </p>
          <% end %>
          <% if @featured_prisoner_inc.articles.present? %>
            <p class="pipe">
              <strong><%=t 'prisoners.labels.charged_under_articles' %></strong>
              <%=
                @featured_prisoner_inc.articles.map { |art|
                  link_to art.number,
                          article_path(art),
                          title: art.desc,
                          "data-toggle" => "tooltip"
                }.join('<i></i>').html_safe
              %>
            </p>
          <% end %>
          <% if @featured_prisoner_inc.description_of_arrest.present? %>
            <div id="featured-description">
              <%= simple_format_no_tags(
                    truncate(
                      sanitize(
                        @featured_prisoner_inc
                          .description_of_arrest.gsub(/<.*?>/, '')
                      ),
                      separator: ' ', length: 300)) %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4 primary-button">
    <a class="btn btn-success primary-button-link" href="<%= methodology_path %>">
      <span class='primary-button-link-text'><%=t '.links.methodology' %></span>
    </a>
  </div>
  <div class="col-sm-4 primary-button">
    <a class="btn btn-success primary-button-link" type="button" href="<%= prisoners_path %>">
      <span class='primary-button-link-text'><%=t '.links.meet_prisoners' %></span>
    </a>
  </div>
  <div class="col-sm-4 primary-button">
    <a class="btn btn-success primary-button-link" type="button" href="<%= articles_path %>">
      <span class='primary-button-link-text'><%=t '.links.see_charges' %></span>
    </a>
  </div>
</div>
<div id="imprisoned-count-timeline" style="width:100%; height:400px;"></div>
<div class="row">
  <div class="col-sm-6">
    <div id="prison-prisoner-counts" style="width:100%; height:500px;"></div>
  </div>
  <div class="col-sm-6">
    <div id="top-10-charge-counts" style="width:100%; height:500px;"></div>
  </div>
</div>

app/views/root/methodology.html.erb
<% page_title t('.title') %>

<%= simple_format_no_tags(@methodology.content) %>